### ISSUE TITLE
Test runner crash: exception in car: () is not a pair

### ISSUE THREAD

**Issue by austinmlv** [exercism/scheme-test-runner#23]
If the test being run fails under either Chez or Guile then the output from stdout may be empty. If so, [`report-results`](https://github.com/exercism/scheme-test-runner/blob/0af6b777ddbb95c034e5a87e6dbe4107c8aec95c/bin/exercise.ss#L16) may be passed an empty list via [`convert`](https://github.com/exercism/scheme-test-runner/blob/0af6b777ddbb95c034e5a87e6dbe4107c8aec95c/bin/exercise.ss#L57) which then gets passed to `failure-count` and in turn `car`, thus causing the test runner to crash by calling `car` on `'()`. `Exception in car: () is not a pair` is printed on stderr.

I have submitted PR #22  to fix this.

**Comment by guygastineau** [comment]
@austinmlv closing since #32 was merged.  Reopen if somehow the issue persists in the website.
