### ISSUE TITLE
Tests fail on exercism but pass on local system

### ISSUE THREAD

**Issue by SohamG** [exercism/scheme-test-runner#40]
Hello,

(I had opened an issue two months ago about the scheme runner being down).

Basically title.

Here's my code for `rna-transcription`

```
(import (rnrs))


(define (dna->rna dna)
   (string-map
    (lambda (c)
      (cond
       ((char=? c #\C) #\G)
       ((char=? c #\G) #\C)
       ((char=? c #\T) #\A)
       ((char=? c #\A) #\U))) dna))
```

Here's a screenshot of tests: 
![image](https://user-images.githubusercontent.com/7116239/183502600-78c90782-45d4-4673-a48c-80ddd9539520.png)

Here's a screenshot of `make guile`:
![image](https://user-images.githubusercontent.com/7116239/183502693-8e799979-67f8-4edb-b1d1-3d17b3131ae8.png)

Please let me know if I can help further.

**Comment by guygastineau** [comment]
If there is no extra information in the GUI fit each failed test, then I think you are using an old version of the tests.  Please try upgrading your exercise.  Our legacy test support should work, but it is more fragile.

**Comment by SohamG** [comment]
@guygastineau How do I do that?

**Comment by SohamG** [comment]
NVM, I clicked the banner and it updated it for me. I guess its working now? I'll play around a bit more and report back

**Comment by guygastineau** [comment]
Maybe the page data was cached?

**Comment by guygastineau** [comment]
@SohamG if you can confirm that this is no longer happening, then I would like to close the issue.

**Comment by SohamG** [comment]
I think its fixed. Closing!
